%% Options 
%% Paths 
Options.Paths = struct( ...
    'path2ROI','D:\data\Oskar\ShortCommunication\CodeGit\roi-paper\ACN\regionofinterest\ParWaitBar',...
    'CDF', 'I:\SCIENCE-PLEN-ECP-AnalytChem\People\Oskar\MasterThesis2\DataFiles\NetCDF', ...
    'CDF_MS2','I:\SCIENCE-PLEN-ECP-AnalytChem\People\Oskar\MasterThesis2\DataFiles\NetCDF',...
    'save2mat','D:\ML\2DxC_MS\MatLab\DataFiles\Mat');

%% ROI 
cd('I:\SCIENCE-PLEN-ECP-AnalytChem\People\Oskar\MasterThesis2\DataFiles\NetCDF\')

% [mzroi, MSroi, RawData,runTime,sizeMZRoI,Rt,trace] = deal(cell(2,1));
Options.ROI = struct( ...
    'minroi',4,...
    'ppm',true,...
    'thresh',50,...
    'wmean',true,...
    'GapAllowed',1,...
    'NumTrace',2,...
    'verbose',true,...
    'prefilter',true,...
    'fillIn',0, ...
    'IMS',false,...
    'RemoveSuffix',13); % Remove the last letters in the sample name in case you have MS2 data obtained in data-independent mode

Options.ROI.mzOptimization = struct( ...
    'MZmultiplyFactors', 1:0.5:4, ...
    'nSamples',4, ...
    'mzerror', 10);
%%
addpath(Options.Paths.path2ROI)
%%
Options.ROI

