%% Options 
%% Paths 
Options.Paths = struct( ...
    'path2ROI','D:\data\Oskar\ShortCommunication\CodeGit\roi-paper\ACN\regionofinterest\ParWaitBar',...
    'CDF', 'D:\data\Oskar\ShortCommunication\CodeGit\roi-paper\ACN\regionofinterest\Test_Data', ...
    'CDF_MS2','D:\data\Oskar\ShortCommunication\CodeGit\roi-paper\ACN\regionofinterest\Test_Data',...
    'save2mat','D:\data\Oskar\ShortCommunication\CodeGit\roi-paper\ACN\regionofinterest\Test_Data');

%% ROI 
% cd('I:\SCIENCE-PLEN-ECP-AnalytChem\People\Oskar\MasterThesis2\DataFiles\NetCDF\')

% [mzroi, MSroi, RawData,runTime,sizeMZRoI,Rt,trace] = deal(cell(2,1));
Options.ROI = struct( ...
    'minroi',4,...
    'ppm',true,...
    'thresh',1000,...
    'wmean',true,...
    'GapAllowed',1,...
    'NumTrace',2,...
    'verbose',true,...
    'prefilter',true,...
    'fillIn',0, ...
    'IMS',false,...
    'SumMSLevels',false,...
    'MS1_Suffix','01.CDF',...
    'MS2_Suffix','02.CDF',...
    'RemoveSuffix',6); % Remove the last letters in the sample name in case you have MS2 data obtained in data-independent mode

Options.ROI.mzOptimization = struct( ...
    'MZmultiplyFactors', 1:0.5:4, ...
    'nSamples',4, ...
    'mzerror', 10);
%%
addpath(Options.Paths.path2ROI)
%%
Options.ROI

