%% Options 
%% Paths 
Options.Paths = struct( ...
    'path2ROI','C:\Users\mht541\Documents\2D_LC_IMS_R\2DIMS\regionofinterest',...
    'CDF', 'C:\Users\mht541\Desktop\MatLab\ShortCommunication\ROIcomp\DataFiles\CDF', ...
    'CDF_MS2','F:/PhD/Matrix/IMS/RPLCxHILIC_CDF',...
    'save2mat','F:/PhD/Matrix/IMS/RPLCxHILIC_CDF\Test_Data');

%% ROI 
% cd('I:\SCIENCE-PLEN-ECP-AnalytChem\People\Oskar\MasterThesis2\DataFiles\NetCDF\')

% [mzroi, MSroi, RawData,runTime,sizeMZRoI,Rt,trace] = deal(cell(2,1));
Options.ROI = struct( ...
    'minroi',4,...
    'ppm',true,...
    'thresh',0,...
    'wmean',true,...
    'GapAllowed',1,...
    'NumTrace',1,...
    'verbose',true,...
    'prefilter',true,...
    'fillIn',0, ...
    'IMS',false,...
    'SumMSLevels',false,...
    'MS1_Suffix','CDF',...
    'MS2_Suffix','CDF',...
    'RemoveSuffix',6); % Remove the last letters in the sample name in case you have MS2 data obtained in data-independent mode

Options.ROI.mzOptimization = struct( ...
    'MZmultiplyFactors', 1:0.5:4, ...
    'nSamples',4, ...
    'mzerror', 10);
%%
addpath(Options.Paths.path2ROI)
addpath([Options.Paths.path2ROI,'\ParWaitBar\'])

%%
Options.ROI

